import type { BandKey, DimensionId } from "../diagnostic/types"

// ODVOZENÝ SOUBOR. Nesahej do něj ručně, přepíše ho scripts/obsah-hrace.cjs.
//
// Výřez výkladu pro vyhodnocení hráče v klubové větvi: sportovní varianta,
// česky a anglicky, jen úroveň dimenzí. Sedí u serveru, protože vyhodnocení
// hráče se počítá tam, aby se klíče nedostaly do prohlížeče.
//
// Rodové značky {mužský|ženský} se rozvinou až při sestavení textu.

export type HracLang = "cs" | "en"

export interface OblastText {
  nazev: string
  uvod: string
  pasma: Record<BandKey, string>
}

export const OBSAH_HRACE: Record<HracLang, Record<DimensionId, OblastText>> = {
  cs: {
    A: {
      nazev: "Identita a vnitřní motivace",
      uvod: "Měří, jak jasně víš, kdo jsi jako sportovec, proč svůj sport děláš a nakolik tvoje sebehodnota stojí na něčem pevnějším než na posledním výsledku. Ukazuje se hlavně v obdobích, kdy se nedaří.",
      pasma: {
        priority: "Tvoje výsledky teď pravděpodobně stojí na vratkém základu. Když nemáš jasno v tom, kdo jsi jako sportovec a proč svůj sport vlastně děláš, každá porážka otřese nejen tvou formou, ale i pocitem vlastní hodnoty. V praxi se to projevuje kolísavou motivací, závislostí na pochvale a tím, že tě neúspěch dokáže rozhodit na celé dny. Hrozí, že budeš plnit představy okolí místo vlastní cesty a dřív nebo později ztratíš chuť. Tato oblast patří na první místo tvého rozvojového plánu: ujasni si hodnoty, své proč a odděl výsledek od vlastní ceny. Poznáš, že se to hýbe, když tě porážka rozhodí na hodiny místo na dny a když dokážeš říct, proč trénuješ, i po špatném zápase.",
        stabilization: "Základ máš položený: víš, kdo jsi a proč trénuješ, a v klidném období z toho dokážeš čerpat. Pod tlakem se ale tato jistota drolí. Po prohraném zápase nebo v období bez formy se přistihneš, že o sobě pochybuješ víc, než je zdravé, a motivace se opírá o výsledky a reakce okolí. Tvým cílem teď není nic nového budovat, ale zpevnit, co už máš, aby to uneslo i porážku a kritiku. Vracej se k hodnotám a ke svému proč právě v náročných týdnech, ne jen když se daří. Nejde o to necítit pochybnost, ale o to, aby nerozhodovala. Po každém zápase si zkus napsat jednu větu o tom, co platí bez ohledu na výsledek.",
        strong: "Víš, kdo jsi, proč sportuješ a na čem stojí tvoje hodnota – a drží to i pod tlakem. Porážka tě zabolí, ale nepřepíše tvou cenu; po pár hodinách dokážeš mluvit o tom, co si z ní bereš. Rozhoduješ se podle vlastních kritérií, ne podle toho, co se od tebe čeká. To ti dává klid, který je v kabině i na hřišti znát. Tuto oblast udržuj vědomě: vracej se k hodnotám při velkých rozhodnutích a používej ji jako kotvu, když se rozkolísá jiná část tvé přípravy. Pozor jen na jedno: pevná identita se snadno změní v neochotu cokoli měnit. Jednou za sezónu si ověř, jestli držíš hodnotu, nebo jen zvyk.",
        elite: "Tato oblast je tvoje konkurenční výhoda. Jasná identita, silné vnitřní proč a sebehodnota nezávislá na výsledku ti dovolují riskovat v momentech, kdy ostatní hrají na jistotu – nemáš totiž co ztratit na vlastní ceně. Dlouhá sezóna, změna role v týmu ani série porážek tě nevykolejí, protože tvoje motivace nestojí na tabulce. Právě na této stabilitě můžeš stavět kariérní strategii: vybírat si výzvy, které tě rozvíjejí, a být oporou pro tým. Hlídej jediné: mluv o svých hodnotách dál nahlas a vracej se k nim – i elitní základ potřebuje údržbu. V týmu je tvoje jistota nakažlivá, ale taky zavazující: to, co řekneš deset minut po prohře, nastavuje tón pro ostatní víc než cokoli od trenéra.",
      },
    },
    B: {
      nazev: "Sebedůvěra a vnitřní dialog",
      uvod: "Měří, jak pevná je tvoje důvěra ve vlastní výkon a jak s tebou mluví tvůj vnitřní hlas v tréninku, v zápase i po chybě. Rozhoduje hlavně v momentech, kdy jde o hodně a na rozmyšlenou není čas.",
      pasma: {
        priority: "Sebedůvěra a vnitřní dialog tě teď systematicky brzdí. Před důležitými zápasy převažují pochybnosti, v klíčových momentech hraješ na jistotu místo řešení, která máš natrénovaná, a po chybě se tvůj vnitřní hlas mění v nemilosrdného kritika. Výsledkem je výkon, který neodpovídá tvé tréninkové úrovni – soupeř neporáží tvoje dovednosti, ale tvůj vztah k sobě. Nejde přitom o povahu, ale o trénovatelnou dovednost. Zařaď tuto oblast na první místo rozvojového plánu: opři sebedůvěru o přípravu a konkrétní důkazy, nastav si jasná pravidla vnitřní řeči pod tlakem a vybuduj rutinu, jak se po chybě vracet do hry. Začni jedním zápasem: vyber si předem jednu situaci, ve které místo jistoty zvolíš natrénované řešení, a po zápase vyhodnoť jen tuhle jednu věc.",
        stabilization: "Základ máš položený: víš, co ti pomáhá, a v běžném tréninku si věříš a mluvíš se sebou konstruktivně. Pod tlakem se to ale zatím rozpadá – vyrovnaná koncovka, silnější soupeř nebo série chyb dokážou probudit pochybnosti i vnitřního kritika. Tvoje sebedůvěra tak kolísá podle posledního výsledku a právě to tě stojí stabilitu výkonu. Cílem není učit se nové dovednosti, ale zpevnit ty stávající, aby fungovaly i v nejtěžších momentech sezóny. Pomůže pevná předstartovní rutina, připravené vnitřní instrukce pro krizové situace a vědomé trénování obojího v zápasovém tlaku, ne jen v klidu. Klíčové je místo nácviku. Dovednost, kterou zkoušíš jen v klidu, pod tlakem nenaskočí; trénuj ji v únavě, ve ztrátě a hned po chybě.",
        strong: "Sebedůvěra a vnitřní dialog patří k silným místům tvého profilu a drží i pod tlakem. Do zápasů vstupuješ s důvěrou opřenou o přípravu, se sebou mluvíš věcně a po chybě se dokážeš rychle vrátit k dalšímu úkolu. To ti dává stabilitu, o kterou se můžeš opřít v rozhodujících fázích sezóny – a kterou z tebe cítí i spoluhráči. Jediné riziko je zanedbání: rutiny a návyky, které tuto oblast drží, potřebují průběžnou údržbu. Používej ji vědomě jako kotvu ve chvílích, kdy pracuješ na slabších částech svého profilu, a záměrně ji vystavuj těžším zkouškám. Zajímavější než další růst je teď šíře: zkus tuhle stabilitu udržet i v roli, na kterou nejsi {zvyklý|zvyklá}, nebo v sezóně, kde se hraje o jiný cíl.",
        elite: "Tvoje sebedůvěra a vnitřní dialog jsou na úrovni, která tvoří konkurenční výhodu. Věříš si nezávisle na posledním výsledku i na jménu soupeře, vnitřní hlas používáš jako nástroj a chyby tě nevychylují – naopak z nich rychle vytěžíš informaci. Nejvíc se to projevuje v největších momentech: zatímco ostatní hrají na jistotu, ty jdeš do řešení. Stavěj na tom identitu i herní strategii: ber si klíčové míče a rozhodující situace, přenášej svůj klid do týmu a předávej své rutiny mladším. Zároveň tuto výhodu dál syť – i elitní sebedůvěra stojí na přípravě a poctivě vedené evidenci úspěchů. Pozor jen na jedno: sebedůvěra opřená o důkazy je pevná, sebedůvěra opřená o sérii výher je křehká. Sleduj, o co se ti opírá zrovna teď.",
      },
    },
    C: {
      nazev: "Koncentrace a řízení pozornosti",
      uvod: "Měří, jak dokážeš zaměřit pozornost na to podstatné, udržet ji navzdory rušení a rychle ji vrátit, když uteče. Nejde o silnou vůli, ale o dovednost, která se dá trénovat.",
      pasma: {
        priority: "Tvoje pozornost v tuto chvíli výrazně ovlivňuje, kolik ze svého potenciálu ve výkonu skutečně ukážeš. Rušivé podněty – diváci, rozhodčí, chování soupeře – i vlastní myšlenky na chyby a výsledek ti pravidelně přebírají kontrolu nad tím, co vnímáš. Výpadky koncentrace přicházejí nečekaně, trvají déle, než si můžeš dovolit, a často padnou právě do klíčových momentů. Dobrá zpráva: koncentrace není vlastnost, ale dovednost, kterou lze systematicky trénovat. Právě proto patří na první místo tvého rozvojového plánu. Každý týden cíleného tréninku pozornosti se ti vrátí přímo ve stabilitě výkonu. Měř si to jednoduše: kolikrát za zápas ti pozornost uteče a jak dlouho trvá návrat. Obě čísla klesají rychleji, než čekáš.",
        stabilization: "Umíš se soustředit a víš, jaké to je být plně v zápase – jen se na tento stav zatím nedokážeš spolehnout. V klidném tréninku pozornost drží, ale pod tlakem, při nepříznivém vývoji nebo po chybě se začne trhat. Rušivé podněty v dobrých dnech filtruješ bez námahy, ve slabších tě stojí energii, která pak chybí jinde. Rozdíl mezi tvým nejlepším a nejslabším výkonem tak nedělá talent, ale stabilita pozornosti. Cílem následujících týdnů proto není učit se nové věci, ale zpevnit to, co už umíš: pevné rutiny, jasné záměry a rychlé návraty. Jediným měřítkem je tady konzistence. Slabé dny nejsou náhoda. Podívej se, co mají společné: obvykle za nimi stojí spánek, únava nebo vynechaná rutina, ne ztráta schopnosti.",
        strong: "Koncentrace patří k oporám tvého výkonu. Dokážeš udržet pozornost na klíčových podnětech i v hlučném prostředí, po chybě se vracíš rychle a diváci ani rozhodčí ti obvykle nevezmou víc než pár vteřin. Pod tlakem se tvoje soustředění nerozpadá – spíš se zužuje na to podstatné. To ti dává výhodu právě v momentech, kdy ostatní začínají těkat. Tuto oblast udržuj vědomě: rutiny, které fungují, neměň – jen je pravidelně procvičuj, aby nezevšedněly. Zároveň ji využívej jako kotvu: když se ti jinde nedaří, návrat k jasnému zaměření pozornosti je tvoje nejjistější cesta zpět do výkonu. Dobré rutiny mají jednu vlastnost: zevšední. Jednou za měsíc si tu svoji projdi vědomě a ověř, jestli ji ještě děláš, nebo už jen předstíráš.",
        elite: "Tvoje schopnost řídit pozornost je na úrovni, která tě reálně odlišuje. Vybíráš si, co vnímáš: hluk tribun, provokace i vlastní chyba projdou kolem, aniž by změnily tvou další akci. Do přítomného okamžiku se dokážeš ponořit i za nepříznivého stavu, a proto tvůj výkon v klíčových momentech spíš roste. Tohle už není jen dovednost, ale konkurenční výhoda – stav na ní identitu i strategii. Vyhledávej situace, ve kterých rozhoduje trpělivost a čistota vnímání pod tlakem – tam máš navrch. A předávej dál, co umíš: tím, že své rutiny vysvětlíš spoluhráčům nebo mladším, je ještě víc zpevníš. Jedno riziko tu je: hluboké soustředění je náročné na energii. Sleduj, kolik ho za týden uneseš, aby se z výhody nestala únava.",
      },
    },
    D: {
      nazev: "Emoční regulace a výkon pod tlakem",
      uvod: "Měří, jak přesně čteš signály svého těla a jak dokážeš řídit emoce a aktivaci, aby tě tlak velkých momentů nabíjel, místo aby tě srážel. Nejvíc je vidět v posledních minutách, ne v tréninku.",
      pasma: {
        priority: "Tlak ti v tuto chvíli bere víc, než kolik ti dává. Nervozita před startem, ztuhlé tělo v klíčových výměnách nebo panika za nepříznivého stavu ti pravidelně srážejí výkon pod úroveň, kterou znáš z tréninku. Signály napětí zachytáváš pozdě a chybí ti spolehlivý postup, jak se během výkonu zklidnit nebo nabudit. Právě proto je tato oblast první položkou tvého rozvojového plánu. Dobrá zpráva: regulace emocí je trénovatelná dovednost, ne vrozená vlastnost. Se systematickým tréninkem dechu, rutin a práce s tlakem se rozdíl mezi tréninkovým a zápasovým výkonem dá výrazně zmenšit. Nezaměňuj to za odvahu. Tělo pod tlakem reaguje stejně u odvážných i opatrných lidí; liší se jen to, co s tou reakcí umíš udělat.",
        stabilization: "Základy máš položené: víš, co s tebou tlak dělá, a v běžných zápasech emoce zvládáš. Když ale sázka stoupne – rozhodující koncovka, důležitý start, ztráta vedení – tvoje regulace přestává být spolehlivá. Někdy se zklidníš přesně ve chvíli, kdy potřebuješ, jindy tě napětí přeroste a výkon kolísá. Cílem této fáze není učit se nové věci, ale udělat z existujících dovedností automatismus. Znamená to trénovat dech a resetovací rutiny přímo v situacích pod tlakem, dokud nebudou fungovat i tehdy, kdy o něco skutečně jde. Přenos je celý trik. Dech, který zvládneš v klidu, nic neznamená; počítá se ten, který zvládneš, když ti buší srdce.",
        strong: "Práce s emocemi a tlakem patří k silným stránkám tvého profilu. Signály těla čteš včas, před startem se dokážeš naladit a v napjatých momentech zápasu si držíš svůj standard. Tlak tě zpravidla nesráží – umíš se zklidnit, když je potřeba, i nabudit, když ti chybí energie. O tuto oblast se můžeš opřít: využívej ji jako kotvu v momentech, kdy jiné části tvé hry kolísají. Udržuj ji pravidelným tréninkem pod tlakem a sleduj, ve kterých vzácných situacích tě emoce ještě dokážou překvapit – právě tam leží poslední rezervy. Poslední rezervy nehledej v nových technikách, ale v situacích, které jsi ještě {nezažil|nezažila}: jiný soupeř, jiné prostředí, jiná role v týmu.",
        elite: "Regulace emocí a výkon pod tlakem jsou tvou konkurenční výhodou. Tam, kde soupeři tuhnou, ty přidáváš – velké momenty tě nabíjejí a tvé rozhodování zůstává čisté i v rozhodujících koncovkách, za vedení i za ztráty. Má smysl proměnit tuto úroveň ve strategii: veď zápasy tak, aby klíčové momenty směřovaly do tvé síly, a buduj si identitu hráče, který je nejlepší, když jde o nejvíc. Zůstaň přitom {pokorný|pokorná} – i elitní regulace potřebuje údržbu. Pravidelně se vystavuj novým formám tlaku, aby tvá výhoda nezevšedněla, a předávej své návyky týmu. Jedna věc se přehlíží: klid pod tlakem stojí energii, i když navenek není vidět. Po velkých zápasech si plánuj zotavení stejně pečlivě jako přípravu.",
      },
    },
    E: {
      nazev: "Odolnost a růstové nastavení mysli",
      uvod: "Tato dimenze měří, jak pevně věříš, že se tvoje schopnosti dají trénovat, jak dlouho vydržíš pracovat bez viditelných výsledků a jak rychle přetavíš porážku nebo kritiku v další krok. Nejvíc se pozná v období, kdy se dlouho nic nelepší.",
      pasma: {
        priority: "Odolnost je teď hlavní brzdou tvého výkonu, a proto patří na první místo rozvojového plánu. Porážka nebo slabší část sezóny v tobě snadno spustí otázku, jestli na to vůbec máš, a dlouhé týdny bez viditelného posunu ti berou chuť trénovat. Kritika od trenéra nebo z okolí v tobě doznívá celé dny a odčerpává energii, kterou potřebuješ v přípravě i v zápase. Dobrá zpráva: odolnost se dá trénovat stejně systematicky jako kondice. Začni jednoduchou strukturou – pevný postup po každé porážce, procesní cíle místo čekání na výsledek a pravidelný zápis toho, co ses {naučil|naučila}. Během několika týdnů se z neúspěchu začne stávat materiál, ne hrozba. Nepleť si odolnost s tvrdostí. Odolný člověk se po ráně vrátí rychle, tvrdý ji jen nedá najevo a zaplatí za to později.",
        stabilization: "Základ odolnosti máš – v klidnějším období bereš chyby jako informaci a dokážeš pracovat na dlouhodobém cíli. Pod tlakem se ale tento přístup drolí: série porážek, dlouhé výkonnostní plató nebo ostrá kritika tě umí vrátit k pochybnostem a starým vzorcům. Tvým úkolem teď není učit se něco nového, ale stabilizovat to, co už umíš, aby to drželo i v nejtěžších týdnech sezóny. Pomůže ti pevná struktura: stejný postup zpracování každé porážky, předem napsané procesní cíle a záznam pokroku, ke kterému se vrátíš, když výsledky nejdou. Konzistence tady vzniká z rituálů, ne z nálady – čím hůř se daří, tím víc se jich drž. Rituál ukáže svou hodnotu až v nejhorším týdnu. Nastav ho proto tak jednoduše, aby se dal dodržet i tehdy, kdy se ti do ničeho nechce.",
        strong: "Odolnost patří k silným místům tvého profilu a drží i pod tlakem. Porážku zpracuješ rychle a věcně, dlouhé období bez výsledků tě nerozloží a kritiku dokážeš využít, aniž by tě osobně zasáhla. Když se sezóna zkomplikuje, můžeš se o tuto oblast vědomě opřít – je to kotva, o kterou se opře zbytek tvého profilu. Udržuj ji aktivně: nevynechávej rozbor prohraných zápasů jen proto, že se zrovna daří, a dál si zapisuj, co se učíš. A využij ji i navenek – tvůj klid po neúspěchu dává jistotu spoluhráčům a zvedá standard celého týmu. Zkontroluj si jednu věc: rozebíráš i vyhrané zápasy? Kdo analyzuje jen prohry, učí se ze čtvrtiny toho, co má k dispozici.",
        elite: "Tvoje odolnost je na úrovni, která ti dává konkurenční výhodu. Tam, kde jiné sportovce porážka zlomí, ty zrychluješ: neúspěch čteš jako data, výkonnostní plató bereš jako běžnou fázi procesu a tvrdá kritika tě zajímá víc než pochvala. Postav na tom identitu – jsi sportovec, který roste z těžkých momentů, a tvoje okolí s tím může počítat. Promítni to i do strategie: vybírej si náročnější soupeře, turnaje a tréninkové podmínky, protože právě tam se tvoje výhoda projeví nejvíc. Hlídej jediné riziko – aby se z odolnosti nestalo přecházení signálů přetížení. I elitní systém potřebuje plánovanou obnovu. Hranice mezi odolností a přecházením únavy je tenká a nepozná se pocitem. Nastav si na ni tvrdá čísla: spánek, klidová tepová frekvence, chuť do tréninku.",
      },
    },
    F: {
      nazev: "Disciplína, návyky a regenerace",
      uvod: "Tato dimenze měří, jak spolehlivě dodržuješ tréninkové návyky nezávisle na náladě a dohledu a jak cíleně pracuješ se spánkem, regenerací a energií. Poznáš ji podle toho, co uděláš ve dnech, kdy se ti nechce.",
      pasma: {
        priority: "Tvoje výsledky teď nejvíce brzdí právě režim. Kvalita tréninku kolísá podle nálady, spánek a regenerace ustupují všemu ostatnímu a energie během dne je spíš náhoda než plán. Část tvého talentu a dřiny se tak ztrácí dřív, než se stihne proměnit ve výkon. Dobrá zpráva: disciplína a návyky se dají trénovat stejně systematicky jako technika. Začni jedním pevným bodem denně – stejný čas spánku, stejná příprava na trénink – a teprve na něj vrstvi další. Tahle oblast patří na první místo tvého rozvojového plánu. Nezačínej pěti změnami naráz. Jeden návyk udržený osm týdnů udělá víc než pět návyků opuštěných po deseti dnech.",
        stabilization: "Základy režimu máš postavené – víš, co ti funguje, a v klidných obdobích to i dodržuješ. Pod tlakem se to ale sype: nabitý týden, únava nebo výpadek motivace stačí k tomu, aby spánek, strava i kvalita tréninku šly stranou. Rozdíl mezi tebou a stabilně výkonným sportovcem teď není ve znalostech, ale v konzistenci. Zaměř se na to, aby tvoje klíčové návyky přežily i špatný den: zjednoduš je, naplánuj je dopředu a měř si, kolik dní v týdnu je skutečně splníš. Cílem není dokonalost, ale spolehlivost. Klíčová je minimální verze. Když si předem určíš, jak vypadá splněný trénink ve špatný den, přestanou špatné dny znamenat nulu.",
        strong: "Režim je tvoje silná stránka. Trénuješ spolehlivě bez ohledu na náladu i na to, jestli tě někdo kontroluje, spánek a regeneraci bereš jako součást přípravy a energii si umíš rozvrhnout. Právě to ti dává stabilitu, o kterou se můžeš opřít v náročných obdobích – když se sype forma nebo přijde tlak, tvoje návyky drží. Udržuj tento standard vědomě: jednou za čas si projdi, které návyky ti skutečně slouží, a pravidelně ověřuj, že regenerace roste spolu se zatížením. Tuhle oblast můžeš používat jako kotvu celého profilu. Sleduj poměr, ne jednotlivé dny: kolik týdnů v řadě ti režim vydržel. Právě série, ne dokonalé dny, dělá rozdíl v celé sezóně.",
        elite: "Tvoje disciplína a práce s regenerací jsou na úrovni, která tvoří konkurenční výhodu. Nespoléháš na motivaci – máš systém, který funguje každý den, a spánek, stravu i zatížení řídíš stejně profesionálně jako samotný trénink. Dlouhodobě to znamená víc kvalitních tréninků, méně zranění a stabilnější formu, než mají soupeři. Postav na tom identitu: nastavuj svými standardy laťku pro celé okolí. Strategicky toho využij v obdobích, kdy ostatní vypadávají – nabité soutěžní bloky, návraty po pauze, přechody na vyšší úroveň. A hlídej jediné riziko: aby se z disciplíny nestala nepružnost. Test pružnosti je jednoduchý: dokážeš vynechat trénink, když to dává smysl, bez pocitu viny? Kdo to nedokáže, systém neřídí, ale systém řídí jeho.",
      },
    },
    G: {
      nazev: "Vztahy, komunikace a prostředí",
      uvod: "Měří, jak otevřená komunikace s trenérem a týmem, zdravé hranice vůči tlaku okolí a kvalita tvého zázemí podporují tvůj sportovní výkon. Je to jediná dimenze, kterou z velké části tvoří lidé kolem tebe.",
      pasma: {
        priority: "Vztahy a prostředí tě teď stojí víc energie, než kolik ti dávají. Pravděpodobně před trenérem nebo vedením zamlčuješ, že něco nezvládáš, vyhýbáš se nepříjemným rozhovorům a tlak okolí – rodiny, klubu i sociálních sítí – necháváš zajít příliš daleko. To není povahový rys, ale chybějící dovednost, a dá se systematicky trénovat. Začni jedním bezpečným vztahem, ve kterém řekneš věci na rovinu, a jednou jasně vyslovenou hranicí. Tahle oblast patří na první místo tvého rozvojového plánu, protože bez funkčního zázemí se všechny ostatní mentální dovednosti opírají o nestabilní základ. Nezačínej u nejtěžšího vztahu. Jeden dobře vedený rozhovor s někým bezpečným tě naučí víc než konfrontace, na kterou ještě nemáš.",
        stabilization: "Základ máš. V klidnějším období komunikuješ s trenérem otevřeně, umíš si říct o podporu a hranice vůči okolí většinou držíš. Pod tlakem se ale objevují staré vzorce: zamlčíš, že něco nezvládáš, odložíš konfliktní rozhovor nebo necháš očekávání rodiny či klubu zajít dál, než je zdravé. Cílem teď není učit se novou dovednost, ale udělat ze stávající spolehlivou rutinu. Vyber si jednu situaci, která tě opakovaně rozhodí – třeba nesouhlas s trenérem – a připrav si pro ni pevný postup předem. Jediné měřítko pro následující týdny je konzistence v zátěži. Mlčení má vždycky cenu, jen se platí později. Zkus si všimnout, co tě jedno zamlčení stálo; bývá to silnější argument než jakékoli předsevzetí.",
        strong: "Vztahy a prostředí patří k tvým silným stránkám – a fungují i pod tlakem. S trenérem či vedením máš vztah postavený na důvěře, dokážeš přiznat chybu, říct si o pomoc a udržet hranice vůči očekáváním okolí. To ti dává vzácnou výhodu: v krizi nezůstáváš {sám|sama} a zpětnou vazbu dostáváš dřív, než se problém rozroste. O tuhle oblast se opírej vědomě, například když pracuješ na slabších místech svého profilu. Zároveň ji udržuj: pravidelné otevřené rozhovory a péče o podpůrné vztahy nejsou samozřejmost, ale trénink, který se vyplácí každý den. Zkontroluj si jedno: mluvíš otevřeně i tehdy, když se daří? Vztahy, které se udržují jen v krizi, v krizi neunesou.",
        elite: "Tohle je tvoje konkurenční výhoda. Kolem sebe máš prostředí, které sis vědomě {vybudoval|vybudovala}: vztah s trenérem postavený na naprosté otevřenosti, lidi, se kterými sdílíš úspěchy i těžkosti, a jasné hranice vůči všemu, co ti bere energii – včetně srovnávání na sociálních sítích. Chyby přiznáváš nahlas, o pomoc si říkáš včas a tlak očekávání umíš pojmenovat dřív, než tě zasáhne. Postav na tom identitu: buď sportovcem, který nastavuje kulturu komunikace v týmu. A využij to strategicky – tvoje zázemí ti dovoluje riskovat, snést vyšší zátěž a růst rychleji než ostatní. Pozor na jedno: prostředí, které sis {vybudoval|vybudovala}, se s každou změnou klubu nebo trenéra staví znovu. Počítej s tím u každého velkého rozhodnutí.",
      },
    },
  },
  en: {
    A: {
      nazev: "Identity and inner motivation",
      uvod: "Measures how clearly you know who you are as an athlete, why you play your sport, and how firmly your self-worth rests on something more solid than your last result. It shows up most clearly in periods when results do not come.",
      pasma: {
        priority: "Right now your performance is standing on shaky ground. When you're not clear about who you are as an athlete or why you play your sport, every defeat shakes more than your form – it shakes your sense of what you're worth. In practice this shows up as motivation that comes and goes, dependence on praise, and losses that stay with you for days. The risk is that you end up living out other people's expectations instead of your own path, and the joy drains away. Make this the first item in your development plan: get clear on your values and your why, and separate your results from your worth. You will know it is shifting when a defeat throws you off for hours rather than days, and when you can still say why you train even after a bad game.",
        stabilization: "The foundation is there: you know who you are and why you train, and in calm periods you can draw on it. Under pressure, though, that certainty starts to crumble. After a lost match or a stretch of poor form you catch yourself doubting more than is healthy, and your motivation leans on results and other people's reactions. Your job now isn't to build something new but to reinforce what you have until it can carry defeat and criticism. Return to your values and your why precisely in the hard weeks, not just when things are going well. The goal is not to feel no doubt, but to keep doubt from deciding. After each match, try writing one sentence about what holds true regardless of the result.",
        strong: "You know who you are, why you compete, and what your worth rests on – and it holds even under pressure. A defeat stings, but it doesn't rewrite your value; within hours you can talk about what you're taking from it. You make decisions by your own criteria rather than by what's expected of you, and that gives you a calm that's noticeable in the locker room and on the field. Keep this area alive deliberately: return to your values at big decision points and use them as an anchor whenever another part of your game gets shaky. Watch one thing: a firm identity easily turns into an unwillingness to change anything. Once a season, check whether you are holding to a value or merely to a habit.",
        elite: "This is a genuine competitive advantage. A clear identity, a strong inner why, and self-worth that doesn't depend on results let you take risks in moments when others play it safe – because nothing that happens on the scoreboard can touch what you're worth. A long season, a changed role in the team, or a losing streak won't derail you, since your motivation doesn't live in the standings. Build your career strategy on this stability: choose the challenges that stretch you and be the steady point others can lean on. Just keep saying your values out loud – even an elite foundation needs maintenance. In a team your steadiness is contagious, and it also binds you: what you say ten minutes after a defeat sets the tone for the others more than anything from the coach.",
      },
    },
    B: {
      nazev: "Confidence and inner dialogue",
      uvod: "Measures how solid your belief in your own game is and how your inner voice speaks to you in training, in competition, and after a mistake. It matters most in moments when the stakes are high and there is no time to think.",
      pasma: {
        priority: "Right now, confidence and inner dialogue are systematically holding your game back. Doubt outweighs belief before big matches, you play it safe in key moments instead of trusting what you've trained, and after a mistake your inner voice turns into a harsh critic. The result is a gap between your training level and what shows up in competition – opponents aren't beating your skills, your self-talk is. This isn't personality; it's a trainable skill. Make it the first block of your development plan: anchor confidence in preparation and concrete evidence, set clear rules for talking to yourself under pressure, and build a routine for returning to the game after errors. Start with a single match: pick one situation in advance where you will choose the trained option instead of the safe one, and afterwards review only that one thing.",
        stabilization: "The foundation is there: you know what helps you, and in everyday training your confidence and self-talk hold up well. Under pressure, though, it still comes apart – a tight finish, a stronger opponent, or a run of errors can wake the doubts and the inner critic back up. Your confidence rises and falls with the last result, and that is exactly what costs you consistency. The goal now is not learning new skills but making the existing ones reliable in the hardest moments of the season. Build a firm pre-competition routine, prepare specific inner instructions for crisis moments, and rehearse both under match pressure, not just in calm conditions. Where you practise is decisive. A skill you rehearse only in calm conditions will not show up under pressure; train it when tired, when behind, and right after a mistake.",
        strong: "Confidence and inner dialogue are strengths of your profile, and they hold up under pressure. You go into matches with belief grounded in your preparation, you talk to yourself in practical terms, and after a mistake you return quickly to the next task. That gives you a stability you can lean on in the decisive stretches of the season – and one your teammates can feel. The main risk is neglect: the routines and habits that keep this area strong need regular upkeep. Use it deliberately as an anchor while you work on the weaker parts of your profile, and keep exposing it to harder tests. More interesting than further growth is breadth: try holding this stability in a role you are not used to, or in a season that is playing for a different goal.",
        elite: "Your confidence and inner dialogue operate at a level that amounts to a competitive advantage. Your self-belief does not depend on last week's results or on the opponent's name, you use your inner voice as a tool, and mistakes become information within seconds. It shows most in the biggest moments: while others play it safe, you go for the solution. Build your identity and game strategy on it – take the key balls and the decisive situations, project your calm into the team, and pass your routines on to younger players. And keep feeding the advantage: even elite confidence runs on preparation and an honest record of evidence. Watch one thing only: confidence built on evidence is solid, confidence built on a winning streak is brittle. Notice which of the two you are leaning on right now.",
      },
    },
    C: {
      nazev: "Concentration and attention control",
      uvod: "Measures how well you lock attention onto what matters, hold it through distraction, and bring it back quickly when it slips. This is not about willpower but about a skill that can be trained.",
      pasma: {
        priority: "Right now, attention is the factor most visibly capping how much of your ability shows up in competition. External noise – the crowd, the referee, an opponent's behaviour – and internal noise like replayed mistakes or thoughts about the result regularly take over what you notice. Lapses arrive without warning, last longer than you can afford, and tend to land in the moments that decide matches. The good news is that concentration is a trainable skill, not a fixed trait. That is exactly why it belongs at the top of your development plan. Every week of deliberate attention training pays back directly in more stable performance. Measure it simply: how many times per match your attention drifts and how long the return takes. Both numbers drop faster than you expect.",
        stabilization: "You know how to concentrate and what being fully locked into a match feels like – you just cannot rely on that state yet. In calm training your focus holds, but under pressure, after a mistake or when the score turns against you, it starts to fray. On good days you handle distractions easily; on weaker days they drain energy you need elsewhere. The gap between your best and worst performances comes mainly from attentional stability, not ability. The goal for the coming weeks is not to learn something new but to make what you already do reliable: firm routines, clear intentions, fast returns. Consistency is the only metric here. Weak days are not random. Look at what they have in common: usually it is sleep, fatigue or a skipped routine behind them, not a lost ability.",
        strong: "Concentration is one of the pillars of your game. You hold attention on the cues that matter even in a loud arena, you come back quickly after mistakes, and the crowd or the referee rarely costs you more than a few seconds. Under pressure your focus narrows onto essentials instead of falling apart. That gives you an edge precisely in the moments when others start to scatter. Maintain this area deliberately: keep the routines that work and refresh them regularly so they stay sharp. And use it as an anchor – when another part of your game wobbles, returning to a clear point of focus is your most reliable way back. Good routines share one trait: they go stale. Once a month, walk through yours deliberately and check whether you are still doing it or merely going through the motions.",
        elite: "Your command of attention operates at a level that genuinely sets you apart. You choose what you perceive: crowd noise, provocation and even your mistakes pass by without changing your next action. You can sink fully into the present moment even when the score is against you, which is why your performance tends to rise in decisive moments. This is no longer just a skill – it is a competitive advantage, so build identity and strategy on it. Seek out contests that are decided by patience and clean perception under pressure; that is where you hold the edge. And teach what you do – explaining your routines to others sharpens them further. One risk remains: deep focus is expensive in energy. Track how much of it you can carry in a week, so the advantage does not turn into fatigue.",
      },
    },
    D: {
      nazev: "Emotion regulation and performance under pressure",
      uvod: "Measures how accurately you read your body's signals and how well you steer emotion and arousal, so that the pressure of big moments lifts your performance instead of breaking it. It is most visible in the closing minutes, not in training.",
      pasma: {
        priority: "Right now, pressure takes more from you than it gives. Pre-start nerves, a tight body in decisive exchanges, or panic when the score turns against you regularly drag your performance below the level you show in training. You catch the signs of tension late, and you lack a reliable way to calm down or fire up mid-performance. That is why this area comes first in your development plan. The good news: emotion regulation is a trainable skill, not a fixed trait. With systematic work on breathing, routines, and pressure training, the gap between training and competition can shrink dramatically. Do not mistake this for courage. Under pressure the body reacts the same way in bold and cautious people alike; what differs is what you can do with that reaction.",
        stabilization: "The foundations are in place: you know what pressure does to you, and in ordinary matches you handle your emotions well. But when the stakes rise – a deciding endgame, a big start, a lead slipping away – your regulation stops being reliable. Sometimes you settle yourself exactly when you need to; other times the tension outgrows you and your performance swings. The goal of this phase is not to learn new tools but to make the ones you have automatic. That means training your breathing and reset routines directly under pressure, until they hold up when something is truly at stake. The transfer is the whole trick. Breathing you can do when calm means nothing; what counts is the breathing you can do when your heart is pounding.",
        strong: "Working with emotion and pressure is one of the strengths of your profile. You read your body's signals early, you can dial yourself in before the start, and in tense moments of a match you hold your standard. Pressure rarely knocks you down – you can calm yourself when needed and raise your energy when it drops. Lean on this area: use it as an anchor when other parts of your game fluctuate. Maintain it through regular pressure training, and note the rare situations where emotion still catches you off guard – that is where your last reserves lie. Do not look for the last reserves in new techniques, but in situations you have not met yet: a different opponent, a different setting, a different role in the team.",
        elite: "Emotion regulation under pressure is your competitive advantage. Where opponents tighten up, you find another gear – big moments energize you, and your decision-making stays clean in deciding endgames, whether you are protecting a lead or chasing a deficit. Turn this level into strategy: shape matches so the key moments play to this strength, and build your identity around being at your best when it matters most. Stay humble about it – even elite regulation needs maintenance. Keep exposing yourself to new forms of pressure so the edge stays sharp, and pass your habits on to the people around you. One thing gets overlooked: calm under pressure costs energy even when nothing shows on the outside. After big matches, plan your recovery as carefully as your preparation.",
      },
    },
    E: {
      nazev: "Resilience and growth mindset",
      uvod: "This dimension measures how firmly you believe your abilities can be trained, how long you can keep working without visible results, and how quickly you turn a loss or criticism into your next step. It shows most in a period when nothing improves for a long time.",
      pasma: {
        priority: "Resilience is currently the main brake on your performance, so it belongs at the top of your development plan. A loss or a weak stretch quickly turns into doubt about whether you have what it takes, and long weeks without visible progress drain your appetite for training. Criticism from a coach or the media stays with you for days and burns energy you need in competition. The good news: resilience trains as systematically as conditioning. Start with simple structure – a fixed routine after every loss, process goals instead of waiting for results, and a regular log of what you learn. Within weeks, setbacks become material instead of a threat. Do not confuse resilience with toughness. A resilient person comes back quickly after a blow; a tough one merely hides it and pays for it later.",
        stabilization: "You have the foundation of resilience – in calmer periods you treat mistakes as information and can work toward a long-term goal. Under pressure that approach crumbles: a string of losses, a long plateau, or sharp criticism can pull you back into doubt and old patterns. Your task now is not to learn something new but to stabilize what you already do, so it holds through the hardest weeks. Firm structure will help: the same routine for processing every loss, pre-written process goals, and a progress log you return to when results dry up. Consistency here comes from rituals, not mood – the worse things go, the tighter you hold them. A ritual proves its worth only in the worst week. So keep it simple enough that you can hold to it even when you feel like doing nothing at all.",
        strong: "Resilience is one of the strengths of your profile, and it holds up under pressure. You process a loss quickly and objectively, a long stretch without results does not unravel you, and you can use criticism without taking the hit personally. When the season gets complicated, lean on this area deliberately – it is the anchor the rest of your profile pulls against. Maintain it actively: keep doing loss reviews even when things are going well, and keep writing down what you learn. And use it outward – your calm after a setback gives teammates certainty and raises the standard of the whole team. Check one thing: do you also review the matches you win? Anyone who analyses only losses learns from a quarter of what is available.",
        elite: "Your resilience operates at a level that gives you a competitive advantage. Where a defeat breaks others, you accelerate: you read failure as data, treat plateaus as a normal phase of the process, and find hard criticism more interesting than praise. Build identity on this – you are the athlete who grows from difficult moments, and the people around you can count on it. Fold it into strategy too: choose tougher opponents, tournaments, and training conditions, because that is where your edge shows most. Guard against one risk only – resilience turning into ignoring signs of overload. Even an elite system needs planned recovery. The line between resilience and ignoring fatigue is thin and cannot be judged by feel. Set hard numbers for it: sleep, resting heart rate, appetite for training.",
      },
    },
    F: {
      nazev: "Discipline, habits and recovery",
      uvod: "This dimension measures how reliably you stick to your training habits regardless of mood or supervision, and how deliberately you manage sleep, recovery and energy. You recognise it by what you do on the days you do not feel like it.",
      pasma: {
        priority: "Right now, your routine is the biggest brake on your performance. Training quality swings with your mood, sleep and recovery give way to everything else, and your energy through the day is more accident than design. That means part of your talent and hard work leaks away before it ever turns into results. The good news: discipline and habits can be trained as systematically as technique. Start with one fixed anchor a day – a set bedtime, a set pre-training routine – and build from there. This area belongs at the top of your development plan. Do not start with five changes at once. One habit held for eight weeks does more than five habits abandoned after ten days.",
        stabilization: "The foundations of your routine are in place – you know what works for you, and in calm periods you follow through. Under pressure, though, it slips: a packed week, fatigue or a dip in motivation is enough for sleep, fuelling and training quality to fall away. The gap between you and a consistently high performer isn't knowledge – it's consistency. Focus on making your key habits survive a bad day: simplify them, plan them in advance, and track how many days a week you actually deliver them. The goal isn't perfection, it's reliability. The minimum version is the key. If you decide in advance what a completed session looks like on a bad day, bad days stop meaning zero.",
        strong: "Your routine is a genuine strength. You train reliably regardless of mood or supervision, you treat sleep and recovery as part of preparation, and you manage your energy with intent. That gives you stability to lean on in demanding periods – when form dips or pressure rises, your habits hold. Maintain this standard deliberately: review from time to time which habits are truly serving you, and make sure recovery scales up whenever the load does. Use this area as an anchor for the rest of your profile. Watch the ratio, not individual days: how many weeks in a row your routine held. It is the streak, not the perfect day, that makes the difference across a season.",
        elite: "Your discipline and recovery management are at a level that constitutes a competitive advantage. You don't rely on motivation – you've built a system that runs every day, and you manage sleep, fuelling and load as professionally as the training itself. Over time that means more quality sessions, fewer injuries and steadier form than your rivals. Build your identity on it: be the athlete whose standards set the bar for everyone around you. Use it strategically in the periods where others fall away – dense competition blocks, comebacks, steps up in level. Watch for one risk only: don't let discipline harden into rigidity. The flexibility test is simple: can you skip a session when it makes sense, without guilt? Anyone who cannot is not running the system, the system is running them.",
      },
    },
    G: {
      nazev: "Relationships, communication and environment",
      uvod: "Measures how open communication with your coach and team, healthy boundaries against outside pressure and the quality of your support base fuel your athletic performance. It is the one dimension shaped largely by the people around you.",
      pasma: {
        priority: "Right now your relationships and environment are costing you more energy than they give back. You probably hide struggles from your coach or management, avoid uncomfortable conversations, and let pressure from family, club and social media go unchallenged for too long. This is not a personality trait – it is a missing skill, and it can be trained systematically. Start with one safe relationship where you say things straight, and one boundary stated out loud. Put this area first in your development plan, because without a functioning support base every other mental skill rests on unstable ground. Do not start with the hardest relationship. One well-handled conversation with someone safe teaches you more than a confrontation you are not ready for.",
        stabilization: "The foundation is there. In calmer periods you communicate openly with your coach, ask for support when you need it, and mostly hold your boundaries. Under pressure, though, old patterns resurface: you hide what you are struggling with, postpone the conflict conversation, or let family and club expectations run further than is healthy. The goal now is not a new skill – it is turning the existing one into a reliable routine. Pick one situation that repeatedly knocks you off course, such as disagreeing with your coach, and prepare a fixed protocol for it in advance. Consistency under load is your only metric for the coming weeks. Silence always has a price, it is just paid later. Try noticing what one thing left unsaid cost you; that tends to be a stronger argument than any resolution.",
        strong: "Relationships and environment are among your strengths – and they hold up under pressure. Your relationship with your coach or management is built on trust; you can admit a mistake, ask for help, and defend your boundaries against outside expectations. That gives you a rare edge: you are never alone in a crisis, and honest feedback reaches you before problems grow. Lean on this area deliberately, for instance while you work on weaker parts of your profile. And keep maintaining it: regular open conversations and care for your support network are not a given – they are training that pays off daily. Check one thing: do you speak openly even when things are going well? Relationships maintained only in a crisis will not hold in one.",
        elite: "This is your competitive advantage. You have deliberately built the environment around you: a coach relationship based on complete openness, people you share both wins and struggles with, and firm boundaries against everything that drains you – including comparison on social media. You admit mistakes out loud, ask for help early, and name outside pressure before it lands. Build your identity on this: be the athlete who sets the communication culture of the team. And use it strategically – your support base lets you take risks, absorb heavier training loads and grow faster than the people around you. Watch one thing: the environment you have built has to be rebuilt with every change of club or coach. Factor that into every big decision.",
      },
    },
  },
}
